### DISCUSSION TITLE
Using set_tuner_band in a HA script or automation

### DISCUSSION THREAD

**Discussion by rarroyo6** [crowbarz/ha-pioneer_async#39] [Q&A] [answered]
I'm trying to use the `set_tuner_band` in an automation and I'm getting the following error:
`The automation "Media: Play the family room media" (automation.media_play_the_family_room_media) has an action that calls an unknown service: media_player.set_tuner_band.`
Is there an example, or a detailed documentation on using `set_tuner_band`, `set_am_tuner_frequency`, or `set_fm_tuner_frequency`?

**Comment by pantherale0** [comment, marked as answer]
Hi,

An example of `set_fm_tuner_frequency`

```
service: pioneer_async.set_fm_tuner_frequency
target:
  entity_id: media_player.living_room_avr
data:
  frequency: 104.5
```

I believe you need to supply the main AVR zone, although in theory it should work on zone 2 etc too as there is only one tuner in these amps.

To change the band, use:

```
service: pioneer_async.select_tuner_band
data:
  band: FM
target:
  entity_id: media_player.living_room_avr
```

@crowbarz I have noticed that the following error is logged when changing the band:

`AVR command select_tuner_band failed: invalid TunerBand specified: FM`

This might be because my AVR is off at the moment though.
