### ISSUE TITLE
Refactor media_player.volume_set for AVRs that don't support setting volume

### ISSUE THREAD

**Issue by Varming73** [crowbarz/ha-pioneer_async#4]
Hi - and thanks for your great work! I got a Pioneer receiver using your addon and it's mostly working great. I noticed that media_player.volume_set doesn't work on the player. This means I can't use a slider to control the volume or make it work with Google Assistant. Am I missing something?

**Comment by crowbarz** [comment]
What model Pioneer AVR do you have? It turns out that not all Pioneer AVRs are capable of setting the volume to a specific level via the serial API. If your model doesn't support it, then there is probably an error logged in the Home Assistant log for volume set command (`VL` for Zone 1)

To configure the integration to emulate volume set using volume up/down steps, enable "Emulate volume set by stepping volume up/down" (`params > volume_step: true }` in `configuration.yaml`) and set "Volume units changed" (`params > volume_step_delta`) appropriate for your unit.

**Comment by Varming73** [comment]
I have the VSX-528. Both media_player.volume_down and media_player.volume_up works perfectly and it's only media_player.volume_set that doesn't work. I've tested with and without volume_step: true but it doesn't seem to do any diffence at all with my (old) receiver.

**Comment by crowbarz** [comment]
Can you enable debug logging on `aiopioneer` to show all the commands sent and responses received when `volume_set` is sent, with and without `volume_step` configured?

**Comment by Varming73** [comment]
Sure - but I've never tried that before. How do I enable the logging and where do I find the logs?

**Comment by Varming73** [comment]
Oh, I just found this:
[https://community.home-assistant.io/t/customizing-existing-component-pioneer-receivers/26369/2](url) where it says:
"Volume set do not work on the VSX-528 so I use VOLUME_STEP instead"

I guess that explains it.

**Comment by crowbarz** [comment]
Can you share your configuration? Enabling `params > volume_step` should allow media_player.volume_set to function properly without the AVR needing to directly support volume set.

**Comment by Varming73** [comment]
Sure thing, with params it looks like this:

```
- platform: pioneer_async
  name: "VSX-528"
  host: 192.168.1.69
  port: 8102
  params:
    volume_step: true
    volume_step_delta: 5
  sources:
    'CD': '01'
    'Tuner': '02'
    'DVD': '04'
    'TV': '05'
    'Sat/Cbl': '06'
    'DVR/BDR': '15'
    'iPod/USB': '17'
    'HDMI/MHL': '48'
    'BD': '25'
    'Adapter': '33'
    'Netradio': '38'
    'Media Server': '44'
    'Favorites': '45'
    'Game': '49'
```

**Comment by crowbarz** [comment]
I see the problem - the documentation was wrong, that param is actually called `volume_steps_only`. Sorry about that, I've updated the documentation. Let me know if correcting the param name fixes the issue.

If you do get it working, then please let me know what `volume_step_delta` should be for model `VSX-528` so I can add a profile for this model to set the default params appropriately.

**Comment by crowbarz** [comment]
Also, to answer an earlier question, enable debugging by adding the following to `configuration.yaml` and then restarting HA:
```yaml
logger:
  logs:
    aiopioneer: debug # enable debug logging for aiopioneer package
    # custom_components.pioneer_async: debug # enable debug logging for integration
```
Debug logging shows you every command that is sent, and the response that is received back from the AVR.
